WebApplication1/Controllers/ReportConController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting;
using Microsoft.Reporting.WebForms;
using System.Web.UI.WebControls;

using System.Data;
using System.Data.SqlClient;
using System.Configuration;

using System.Web.Security;
using System.IO;
using ReportViewerForMvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    public class ReportConController : Controller
    {
        // GET: ReportCon
        public string constring = ConfigurationManager.ConnectionStrings["adoConnectionstring"].ToString();

        public ActionResult signout()
        {
            Session["username"] = null;
            Session["userid"] = null;
            Session["userimagepath"] = null;
            Session["accountrole"] = null;

            return RedirectToAction("Index", "UserLogin");
        }

        MyDataSet dsReport = new MyDataSet();
        public ActionResult ReportListofComliantBusiness()
        {
            using (SqlConnection connection = new SqlConnection(constring))
            {

                ReportViewer reportviewer = new ReportViewer();
                reportviewer.ProcessingMode = ProcessingMode.Local;
                reportviewer.SizeToReportContent = true;
                reportviewer.Width = Unit.Percentage(200);
                reportviewer.Height = Unit.Percentage(200);

                SqlCommand command = connection.CreateCommand();
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.CommandText = "sp_ReportListOfBusiness";
                //command.Parameters.AddWithValue("@ClassificationId", ClassificationId);
                //command.Parameters.AddWithValue("@BusinessId", BusinessId);
                SqlDataAdapter sqlDA = new SqlDataAdapter(command);
                DataTable dtListofBusiness = new DataTable();

                connection.Open();

                //sqlDA.Fill(dsReport, dsReport.sp_ReportListOfBusiness.TableName);
                sqlDA.Fill(dsReport, dsReport.sp_ReportListOfBusiness.TableName);
                string path = Path.Combine(Server.MapPath("~/Reports"), "Report1.rdlc");
                //reportviewer.LocalReport.ReportPath = Server.MapPath(@"/Reports/Report1.rdlc");
                reportviewer.LocalReport.ReportPath = path;
                reportviewer.LocalReport.DataSources.Add(new ReportDataSource("MyDataSet", dsReport.Tables[0]));
                ViewBag.ReportViewer = reportviewer;

                connection.Close();

                return View();


            }
        }


        NEWDATASET dsReport2 = new NEWDATASET();

        public ActionResult GraphReportofBusinessPerClassification()
        {

            using (SqlConnection connection2 = new SqlConnection(constring))
            {

                ReportViewer reportviewer2 = new ReportViewer();
                reportviewer2.ProcessingMode = ProcessingMode.Local;
                reportviewer2.SizeToReportContent = true;
                reportviewer2.Width = Unit.Percentage(200);
                reportviewer2.Height = Unit.Percentage(200);

                SqlCommand command2 = connection2.CreateCommand();
                command2.CommandType = System.Data.CommandType.StoredProcedure;
                command2.CommandText = "ReportCountofBusinessPerClassification";
                //command.Parameters.AddWithValue("@ClassificationId", ClassificationId);
                //command.Parameters.AddWithValue("@BusinessId", BusinessId);
                SqlDataAdapter sqlDA2 = new SqlDataAdapter(command2);
                DataTable dtListofBusiness2 = new DataTable();

                connection2.Open();
                //sqlDA.Fill(dtListofBusiness);

                sqlDA2.Fill(dsReport2, dsReport2.ReportCountofBusinessPerClassification.TableName);
                string path2 = Path.Combine(Server.MapPath("~/Reports"), "Report2.rdlc");
                //reportviewer.LocalReport.ReportPath = Server.MapPath(@"/report/Report1.rdlc");
                reportviewer2.LocalReport.ReportPath = path2;
                reportviewer2.LocalReport.DataSources.Add(new ReportDataSource("NEWDATASET", dsReport2.Tables[0]));
                ViewBag.ReportViewer2 = reportviewer2;

                connection2.Close();

            }

            return View();

        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: hotpink">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tourism Business Registration", "Index", "UserLogin", new { area = "" }, new { @class = "navbar-brand", @style = "color: white" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", null, new { @style = "color: white" })</li>*@

                    <li class="dropdown">
                        <a style="color: white" href="#" class="dropdown-toggle" data-toggle="dropdown"
                        role="button" aria-expanded="false">Reports<caret class="caret"></caret></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("List of Businesses", "ReportListofComliantBusiness", "ReportCon")</li>
                            <li>@Html.ActionLink("Chart", "GraphReportofBusinessPerClassification", "ReportCon")</li>


                        </ul>

                        @*@{
                    if (Session["username"] != null)
                    {

                        <li><a style="color: white" ;">Edit User Account Details</a></li>
                        <li>@Html.ActionLink("Logout", "Index", "UserLogin", null, new { @style = "color: white" })</li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("Login", "Index", "UserLogin", null, new { @style = "color: white" })</li>
                        <li>@Html.ActionLink("Register", "NewUserAccountRegistration", "UserLogin", null, new { @style = "color: white" })</li>

                    }

                }*@
                        @*</li>*@


                    @*<li>@Html.ActionLink("About", "About", "Home", null, new { @style = "color: white" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", null, new { @style = "color: white" })</li>*@
                </ul>
                @*@Html.Partial("_LoginPartial")*@
                @Html.Partial("_LoginPartial2")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Online Tourism Business Registration</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_LoginPartial2.cshtml
@using Microsoft.AspNet.Identity
@if (Session["username"] != null)
{
    //using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right", @style = "color: white" }))
    //{
        @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
    @*<li>
            @Html.ActionLink("" + Session["username"].ToString() + "", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" , @style = "color: white" })
        </li>*@
    <li>
        <a class="navbar-brand">
            @if (Session["UserImagePath"] == null || Session["UserImagePath"] == "")
            {
                Session["UserImagePath"] = "~/UserImages/UserDefaultPic.png";
            }
            <img src="@Url.Content(Session["UserImagePath"].ToString())" alt="" height="25" width="25" style="border-radius:50%" />
        </a>
    </li>
    <li class="dropdown">

        <a style="color: white" href="#" class="dropdown-toggle" data-toggle="dropdown"
           role="button" aria-expanded="false">@Session["username"].ToString()<caret class="caret"></caret></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Edit Account", "EditUserAccount", "UserLogin")</li>
            @*<li>@Html.ActionLink("Chart", "GraphReportofBusinessPerClassification", "ReportCon")</li>*@

           
        </ul>
    </li>
    <li>@Html.ActionLink("Logout", "signout", "UserLogin", htmlAttributes: new { @style = "color: white" })</li>

    @*<li><a href="javascript:document.getElementById('logoutForm').submit()" style="color: White">Log off</a></li>*@
    </ul>
}
    @*}*@
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Register", "NewUserAccountRegistration2", "UserLogin", routeValues: null, htmlAttributes: new { id = "registerLink", @style = "color: white" })</li>
        <li>@Html.ActionLink("Log in", "Index", "UserLogin", routeValues: null, htmlAttributes: new { id = "loginLink", @style = "color: white" })</li>
    </ul>
}